### PR TITLE
update root component before every find

### PR DESCRIPTION
**Pull request by iofjuupasli**

### CODE REVIEW

**Comment by kirill-konshin** [comment]
Just ran into this issue.
@etiennedi please merge, this is safe.

**Comment by kirill-konshin** [comment]
Ping!!!

**Comment by etiennedi** [comment]
Merged. npm release will follow tonight.

**Comment by kirill-konshin** [comment]
Please make NPM release as promised. So far I see old 1.0.9.

**Comment by vieron** [comment]
npm release please 🙏  :)

**Comment by tobias-bahls** [comment]
👍  please npm release :D

**Comment by vieron** [comment]
@etiennedi Can I help to get this released?

**Pull request merged**
